name: build-vsix

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 👇 Fuerza Node 16 (compat. con Webpack 4)
      - uses: actions/setup-node@v4
        with:
          node-version: '16.x'

      - name: Ver versiones
        run: |
          node -v
          npm -v

      - name: Instalar dependencias (npm)
        run: |
          if [ -f package.json ]; then
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
          else
            echo "No hay package.json en la raíz; busco uno..."
            first=$(find . -path "*/node_modules/*" -prune -o -name package.json -print | head -n1 || true)
            if [ -z "$first" ]; then
              echo "::error::No se encontró package.json"; exit 1
            fi
            dir=$(dirname "$first")
            echo "Usando $dir"
            cd "$dir"
            if [ -f package-lock.json ]; then
              npm ci
            else
              npm install --no-audit --no-fund
            fi
          fi

      - name: Instalar vsce y empaquetar
        run: |
          npm i -g @vscode/vsce
          vsce package

      - name: Subir VSIX
        uses: actions/upload-artifact@v4
        with:
          name: vsix
          path: "**/*.vsix"
